name: SlonJopaPlugin
version: '1.0.0'
main: com.galyakyxnja.slonjopa.Main
api-version: '1.21'
author: GalyaKyxnya
description: Плагин для сервера Жопа слона!
commands:
  jopa:
    description: Призвать Хозяина Жопы
    usage: /jopa
  jopas:
    description: Выдать часть слона
    usage: /jopas <часть>
    permission: slonjopa.admin
permissions:
  slonjopa.admin:
    description: Доступ к админским командам
    default: op